import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex h-screen overflow-hidden">
          <Toaster
            position="bottom-right"
            reverseOrder={false}
            toastOptions={{
              className: "",
              duration: 2000,
              style: {
                border: "1px solid #713200",
                padding: "16px",
                color: "#713200",
              },
              success: {
                duration: 2000,
              },
              error: {
                duration: 2000,
              },
            }}
          />
          {children}
        </main>
      </body>
    </html>
  );
}
