import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/myComponents/Layout/Sidebar";
import Navbar from "@/components/myComponents/Layout/Navbar";
import Footer from "@/components/myComponents/Layout/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="grid grid-cols-[1fr_5fr]">      
            <Sidebar />    
          <div>
              <Navbar />
            {children}
              <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
